language: node_js
node_js:
  - "node"
install:
  - npm install
branches:
  only:
  - develop
  - release/*
  - hotfix/*
  - master
script:
  - npm run build
  - npm run deploy $DEV02_HOST $DEV02_USER $DEV02_PASS